
name: Publish Docker image

on:
  workflow_run:
    workflows:
      - main
    branches:
      - master
    types:
      - completed
      
env:
  IMAGE_NAME: robo-gym-rs
  TAG_NAME: cuberoom
      
jobs:
  push_to_registry:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build and push Docker image
        uses: docker/build-push-action@v2.6.1
        with:
          context: .
          push: true
          tags: ${{ env.TAG_NAME }}
          labels: ${{ env.IMAGE_NAME }}
  
